apiVersion: v1
kind: Secret
metadata:
  name: permission-manager
  namespace: permission-manager
type: Opaque
stringData:
  PORT: "4000" # port where server is exposed
  CLUSTER_NAME: "default" # name of the cluster to use in the generated kubeconfig file
  CONTROL_PLANE_ADDRESS: "https://127.0.0.1:6443" # full address of the control plane to use in the generated kubeconfig file
  BASIC_AUTH_PASSWORD: "alvaro" # password used by basic auth (username is `admin`)
